---
title: "課堂練習模版"
author: "phias"
date: "2020-12-09"
output: output_format
params:
  id: "410674270"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓',
  '新竹市北區竹光路99號',
  '金門縣金城鎮賢庵里山前33號',
  '臺中市南屯區工業區二十四路23號1樓')
```


```{r}
str_extract(
  addresses,
  "(?<=[縣市])[\u4E00-\u9FFF]+[區鎮]"
)
str_extract(
  addresses,
  "(?<=[縣市])[^區]+[區鎮]"
)
```
```{r}
sameIdentities <- c("臺北市", "台北市", "台北大學", "臺北大學", "基隆市")

str_detect(
  sameIdentities, pattern="[台臺]")
str_view_all(
  sameIdentities, pattern="[台臺]")
str_extract(
  sameIdentities, pattern="[台臺]北市")
str_subset(
  sameIdentities, pattern="[台臺]北市")
```
```{r}
library(lubridate)
originD <- ymd(c(
  "2020-01-03", 
  "2020-02-11",
  "2020-03-08", 
  "2020-05-07",
  "2020-09-20",
  "2020-10-10",
  "2020-11-07",
  "2020-12-05"))
originD

# 由breaks將2020-01-03（含）至2020-12-06（不含）分成三份
cutD <- cut(originD,
            breaks = 
              c(
                min(originD),
                ymd(c(
                "2020-03-08",
                "2020-05-22",
                "2020-07-20",
                "2020-10-11")),
                max(originD)+days(1)
              ))
              
cutD

levels(cutD) <- c("沒事","事件一","沒事","事件二","沒事")

df <- data.frame(
  origin=originD,
  cut=cutD
)
View(df)
```

