---
title: "課堂練習模版"
author: "phias"
date: "2020-10-14"
output: output_format
params:
  id: "410674270"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```


```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```
##character
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

##factor #省記憶體空間
```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```


```{r}
majors10_char
majors10_factor
```
##呈現fator編碼
```{r}
as.integer(majors10_factor)
```

```{r}
a <- factor(c("一","二","三"))
a
```

```{r}
"1.5"+"2"
1.5+2
```

```{r}
class("1.5")
class("2")
```

```{r}
as.numeric("1.5")
```

##字串轉數字
```{r}
a <- "1"
as.numeric(a) ->a #注意要回傳
a+4
```




