---
title: "課堂練習模版"
author: "phias"
date: "2020-11-25"
output: html_document
params:
  id: "410674270"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
str(example)


```
###transpose
```{r}
tr_example <- purrr::transpose(example)
str(tr_example)
```
###data frame
```{r}
df_example <- as.data.frame(example)
```

```{r}
tr_tr_example <- purrr::transpose(tr_example) # 無法df
```

```{r}
library(purrr)
purrr::map(tr_tr_example,
    unlist) -> map_tr_example2 # map才能df
df_example2 <- 
  as.data.frame(map_tr_example2)
```

```{r}
example2 <- 
  list(
    name=c("John", "Mary"),
    height=list(178, 168), # not atomic vector
    weight=c(88, 56, 70) # not the same length as other elements
  )
str(example2)

as.data.frame(example2)
```

```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-10","11-15"), 15, replace=T)
ages_chr

unique(ages_chr)

ages_fct1 <- 
  factor(
    ages_chr
  )
table(ages_fct1)
table(ages_chr)
```

###NA
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

x2
is.na(x2) #NA的判定語法
```

```{r}
c(22,NA,18) -> a
#a==NA ##這個判定沒有用
is.na(a) #判斷NA的時候必須使用is.na
```

```{r}
print(example[c("name","weight")])

pick_na <- is.na(example$weight)
example$name[pick_na]
```

```{r}
print(example[c("name","hobby")])

pick_loveFood <- stringr::str_detect(example$hobby,c("美食","旅遊"))
pick_loveFood
example$name[pick_loveFood]
```
###4.4.3 extra tool
```{r}
# 使用list的工具
df_example$name[c(1,4)]

# 使用data frame的延伸工具`[.row, .column]`
df_example[c(1,4), "name"]
df_example[c(1,4), c("name","residence")]

# 只使用list工具
list(
  name=df_example$name[c(1,4)],
  residence=df_example$residence[c(1,4)]
)
# 要小心以下用法是error
df_example[c("name","residence")][c(1,4)]
```
###奇數、偶數
```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
sequenceNums %% 2 # 餘數為1則是奇數，0則是偶數
pick_evens <- (sequenceNums %% 2) == 1
sequenceNums[pick_evens]
```

###sort
```{r}
# 由小排到大
##1
a<-sort(x) 
fac_a<-factor(x,levels = a)
##2
fac_a<-factor(x,levels = rev(b))

#由大排到小
##1
b<-sort(x, decreasing=T) 
fac_b<-factor(x,levels = b)
##2
fac_b<-factor(x,levels = rev(a))

```

